export const GET_PROJECTS = "GET_PROJECTS";
export const POST_PROJECTS = "POST_PROJECTS";
export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
export const DESTROY_PROJECTS = "DESTROY_PROJECTS";

export const GET_TASKS = "GET_TASKS";
export const POST_TASKS = "POST_TASKS";