export const POST_PROJECT = "POST_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DESTROY_PROJECT = "DESTROY_PROJECT";
export const DEFINE_PROJECT = "DEFINE_PROJECT";
export const POST_NEWS = "POST_NEWS";
export const TO_NOTIFY = "TO_NOTIFY";
